# Configuração do site
title: Razekky Music # Titulo do site
email: Bookings.dj@yahoo.com # email
description: > # 
baseurl: "" # 
url: "" # 

# redes sociais
twitter_username: djrazzeky
facebook_username: djrazzeky
soundcloud_username: djrazzeky

# 
markdown: kramdown
